const LANG='EN';
const ru=LANG==='RU', prefix=ru?'33':'29', page=await figma.getNodeByIdAsync(prefix+':2');
await figma.setCurrentPageAsync(page);
await Promise.all(['Regular','Medium','Semi Bold','Bold'].map(style=>figma.loadFontAsync({family:'Inter',style})));
const v=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).map(v=>[v.name,v]));
const created=[],removed=[],mutated=[],links=[];
const C={Primary:'113:240',Secondary:'113:242',Quiet:'113:244',BadgeNeutral:'113:247',BadgeSuccess:'113:249',BadgeWarning:'113:251',SwitchOn:'113:254',SwitchOff:'113:256'};
for(const key of Object.keys(C))C[key]=await figma.getNodeByIdAsync(C[key]);
const p=(key)=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',v[key]);
const tr=n=>(created.push(n.id),n);
const bind=(n,k,name)=>n.setBoundVariable(k,v[name]);
const rnd=(n,r='radius/lg')=>['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'].forEach(k=>bind(n,k,r));
const L=(en,rus)=>ru?rus:en;
function auto(parent,name,dir='VERTICAL',width=342,gap=16,pad=0,bg=null){let n=tr(figma.createAutoLayout());parent.appendChild(n);n.name=name;n.layoutMode=dir;n.resize(width,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.itemSpacing=gap;n.fills=bg?[p(bg)]:[];for(const k of ['paddingLeft','paddingRight','paddingTop','paddingBottom'])n[k]=pad;const space=Object.values(v).find(a=>a.resolvedType==='FLOAT'&&a.name.startsWith('spacing/')&&Object.values(a.valuesByMode)[0]===gap);if(space)n.setBoundVariable('itemSpacing',space);return n;}
function text(parent,s,size=14,line=20,color='color/text/secondary',weight='Regular',w=null){const n=tr(figma.createText());parent.appendChild(n);n.name=s.length<48?s:'Copy / '+s.slice(0,42);n.fontName={family:'Inter',style:weight};n.fontSize=size;n.lineHeight={unit:'PIXELS',value:line};n.characters=s;n.fills=[p(color)];n.textAutoResize='HEIGHT';n.resize(w??Math.max(1,parent.width-parent.paddingLeft-parent.paddingRight),line);n.textAutoResize='HEIGHT';return n;}
function title(parent,s,desc){const g=auto(parent,'Heading','VERTICAL',342,8);text(g,s,28,34,'color/text/primary','Semi Bold');if(desc)text(g,desc,14,21);return g;}
function card(parent,name,w=342,pad=20,gap=16){const g=auto(parent,name,'VERTICAL',w,gap,pad,'color/bg/surface');rnd(g,'radius/xl');g.strokes=[p('color/border/default')];g.strokeWeight=1;return g;}
function row(parent,name,w=null,gap=12){const g=auto(parent,name,'HORIZONTAL',w??parent.width-parent.paddingLeft-parent.paddingRight,gap);g.counterAxisAlignItems='CENTER';return g;}
function badge(parent,s,tone='Neutral'){const i=tr(C['Badge'+tone].createInstance());parent.appendChild(i);i.setProperties({'Label#113:23':s});i.name='Status / '+s;i.primaryAxisSizingMode='AUTO';return i;}
function button(parent,s,dest=null,style='Primary',width=null){const i=tr(C[style].createInstance());parent.appendChild(i);i.name='Action / '+s;i.resize(width??parent.width-parent.paddingLeft-parent.paddingRight,48);i.setProperties({'Label#113:19':s});if(dest)links.push([i,dest]);return i;}
function kv(parent,k,val){const r=row(parent,'Detail / '+k);r.primaryAxisAlignItems='SPACE_BETWEEN';text(r,k,14,20,'color/text/secondary','Regular',r.width-105);text(r,val,14,20,'color/text/primary','Medium',93).textAlignHorizontal='RIGHT';return r;}
function metric(parent,label,val,w=145){const g=auto(parent,'Metric / '+label,'VERTICAL',w,4);text(g,label,12,18);text(g,val,22,28,'color/text/primary','Semi Bold');return g;}
function chart(parent,h=100){const width=parent.width-parent.paddingLeft-parent.paddingRight;const g=auto(parent,'Chart / simulated net result','VERTICAL',width,8);const svg=`<svg width="${width}" height="${h}" viewBox="0 0 302 100" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#8B75F3" stop-opacity=".20"/><stop offset="1" stop-color="#8B75F3" stop-opacity="0"/></linearGradient></defs><path d="M0 28H302M0 60H302M0 92H302" stroke="#A3ADC2" stroke-opacity=".12" stroke-width=".7"/><path d="M2 80C18 80 22 68 39 68S62 83 81 71S103 63 118 65S139 45 155 45S178 53 194 36S213 46 231 30S258 33 272 21S289 21 300 11L300 99H2Z" fill="url(#a)"/><path d="M2 80C18 80 22 68 39 68S62 83 81 71S103 63 118 65S139 45 155 45S178 53 194 36S213 46 231 30S258 33 272 21S289 21 300 11" fill="none" stroke="#A998FF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;const n=tr(figma.createNodeFromSvg(svg));g.appendChild(n);n.name='Plot / one continuous series';n.resize(width,h);const r=row(g,'Time axis',width);r.primaryAxisAlignItems='SPACE_BETWEEN';text(r,L('Sep 1','1 сен'),11,16,'color/text/secondary','Regular',80);const t=text(r,L('Sep 30','30 сен'),11,16,'color/text/secondary','Regular',80);t.textAlignHorizontal='RIGHT';return g;}
function notice(parent,s,tone='info'){const g=auto(parent,'Note','VERTICAL',342,0,16,tone==='warning'?'color/warning/bg':'color/bg/elevated');rnd(g);text(g,s,13,20,tone==='warning'?'color/warning/text':'color/text/secondary');return g;}
function top(screen){const h=row(screen,'App bar',342,12);h.resize(342,40);h.primaryAxisSizingMode='FIXED';h.primaryAxisAlignItems='SPACE_BETWEEN';text(h,'shadow',20,26,'color/text/primary','Semi Bold',170);badge(h,L('Demo','Демо'));return h;}
function progress(parent,n){const r=row(parent,'Setup progress',342,8);for(let j=0;j<4;j++){const b=tr(figma.createRectangle());r.appendChild(b);b.name='Step '+(j+1);b.resize(79.5,3);b.cornerRadius=1.5;b.fills=[p(j<n?'color/accent/default':'color/border/default')];}return r;}
function footer(s,label,dest,back=null){const f=auto(s,'Action area','VERTICAL',342,8);button(f,label,dest);if(back)button(f,L('Back','Назад'),back,'Quiet');return f;}
function nav(screen,selected){const n=row(screen,'Bottom navigation',342,6);n.resize(342,64);n.primaryAxisSizingMode='FIXED';const defs=[['Overview','Обзор',236,'M3 10L12 3L21 10V21H15V14H9V21H3Z'],['Traders','Трейдеры',31,'M4 20V13M10 20V8M16 20V3M22 20H2'],['Activity','События',289,'M4 5H20M4 12H20M4 19H15']];for(const [en,ruLabel,dest,path] of defs){const item=auto(n,'Navigation / '+en,'VERTICAL',110,4,4,selected===dest?'color/bg/elevated':null);item.resize(110,56);item.primaryAxisSizingMode='FIXED';item.counterAxisAlignItems='CENTER';item.primaryAxisAlignItems='CENTER';rnd(item,'radius/md');const svg=tr(figma.createNodeFromSvg(`<svg width="22" height="22" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="${path}" fill="none" stroke="${selected===dest?'#C3B5FF':'#A3ADC2'}" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`));item.appendChild(svg);const t=text(item,L(en,ruLabel),11,16,selected===dest?'color/text/primary':'color/text/secondary','Medium',102);t.textAlignHorizontal='CENTER';if(selected!==dest)links.push([item,prefix+':'+dest]);}return n;}
const rollback=tr(figma.createFrame());page.appendChild(rollback);rollback.name='Rollback / previous mobile '+LANG+' / 2026-09-28';rollback.x=0;rollback.y=2200;rollback.resize(4380,940);rollback.fills=[];rollback.clipsContent=false;const ids=[3,31,90,127,158,187,210,236,289,328];const summaries=[];
for(const id of ids){
const s=await figma.getNodeByIdAsync(prefix+':'+id);if(!s||s.type!=='FRAME')throw Error('Expected screen '+id);const backup=tr(figma.createFrame());rollback.appendChild(backup);backup.name='Previous / '+s.name;backup.resize(s.width,s.height);backup.x=ids.indexOf(id)*438;backup.y=0;backup.fills=s.fills;backup.clipsContent=true;for(const child of [...s.children]){const ox=child.x,oy=child.y;backup.appendChild(child);child.x=ox;child.y=oy;mutated.push(child.id);}mutated.push(s.id);s.layoutMode='VERTICAL';s.resize(390,844);s.primaryAxisSizingMode='FIXED';s.counterAxisSizingMode='FIXED';s.paddingLeft=24;s.paddingRight=24;s.paddingTop=24;s.paddingBottom=24;s.itemSpacing=24;s.fills=[p('color/bg/canvas')];s.effects=[];s.clipsContent=true;s.cornerRadius=24;s.setExplicitVariableModeForCollection('VariableCollectionId:2:3','2:1');top(s);const body=auto(s,'Content','VERTICAL',342,20);body.layoutSizingVertical='FILL';
if(id===3){title(body,L('Copy with confidence.\nStart with a demo.','Копируйте осознанно.\nНачните с демо.'),L('Follow a trader with a virtual budget. See every action before using real money.','Наблюдайте за трейдером с виртуальным бюджетом. Сначала изучите каждое действие.'));const c=card(body,'Demo preview');const r=row(c,'Trader');text(r,'0x7A…91F',18,24,'color/text/primary','Semi Bold',205);badge(r,L('Example','Пример'));text(c,L('Simulated result · 30 days','Результат симуляции · 30 дней'),12,18);text(c,'+$24.60',32,38,'color/text/primary','Semi Bold');chart(c,86);text(c,L('Illustrative data. Returns are not guaranteed.','Данные для примера. Доход не гарантирован.'),12,18);const langs=row(body,'Choose language',342,10);button(langs,'English',ru?'https://www.figma.com/proto/lxPP2um7FvIbt02K8eeH4T?node-id=29-3&starting-point-node-id=29%3A3':null,ru?'Secondary':'Primary',166);button(langs,'Русский',ru?null:'https://www.figma.com/proto/lxPP2um7FvIbt02K8eeH4T?node-id=33-3&starting-point-node-id=33%3A3',ru?'Primary':'Secondary',166);}
if(id===31){title(body,L('Find your trader','Найдите трейдера'),L('Compare copy quality, results and risk.','Сравните качество копирования и риск.'));const c=card(body,'Trader / 0x7A91F');const r=row(c,'Identity');text(r,'0x7A…91F',21,28,'color/text/primary','Semi Bold',210);badge(r,'82 / 100');text(c,'Polymarket',12,18);const metrics=row(c,'Performance',302,12);metric(metrics,L('30d net result','За 30 дней'),'+12.8%',145);metric(metrics,L('Max drawdown','Макс. просадка'),'6.4%',145);chart(c,52);kv(c,L('Copyable signals','Копируемость'),'94%');kv(c,L('Suggested budget','Бюджет от'),'$200');button(c,L('View trader','Открыть трейдера'),prefix+':90','Secondary');const other=card(body,'Trader / 0x29B4C',342,16,8);text(other,'0x29…B4C · Limitless',16,22,'color/text/primary','Medium');text(other,L('Quality 74/100 · Drawdown 4.1%','Качество 74/100 · Просадка 4,1%'),13,20);}
if(id===90){title(body,'0x7A…91F',L('Polymarket · 11 months of history','Polymarket · 11 месяцев истории'));const c=card(body,'Performance');const rr=row(c,'Quality');text(rr,L('Copy quality','Качество копирования'),14,20,'color/text/secondary','Regular',200);badge(rr,'82 / 100');text(c,L('30-day simulation after virtual fees','Симуляция за 30 дней с учётом комиссий'),12,18);text(c,'+$24.60',32,38,'color/text/primary','Semi Bold');chart(c,94);const stats=row(body,'Risk metrics',342,12);const a=card(stats,'Drawdown',165,16,4);text(a,L('Max drawdown','Макс. просадка'),12,18);text(a,'6.4%',24,30,'color/text/primary','Semi Bold');const b=card(stats,'Copyable',165,16,4);text(b,L('Copyable signals','Копируемость'),12,18);text(b,'94%',24,30,'color/text/primary','Semi Bold');notice(body,L('The score describes copy quality. It does not predict profit.','Рейтинг оценивает качество копирования, а не будущий доход.'));}
if(id===127){progress(body,1);title(body,L('Set your demo budget','Бюджет демо'),L('The maximum virtual balance this trader can use.','Максимальная виртуальная сумма для этого трейдера.'));const c=card(body,'Budget input');text(c,L('Virtual budget · USD','Виртуальный бюджет · USD'),13,20);text(c,'$200',40,48,'color/text/primary','Semi Bold');text(c,L('No deposit. No real money.','Без пополнения и реальных денег.'),13,20);const presets=row(body,'Suggested budget',342,10);for(const val of ['$50','$100','$200'])button(presets,val,null,val==='$200'?'Primary':'Secondary',107.3);const e=card(body,'Example activity');text(e,L('What would this look like?','Как выглядит пример'),16,22,'color/text/primary','Semi Bold');kv(e,L('Monthly turnover','Оборот за месяц'),'$800');kv(e,L('Virtual fee estimate','Расчёт комиссии'),'$4.80');text(e,L('Example at a 0.60% average fee. No fee is charged in the demo.','Пример при средней ставке 0,60%. В демо комиссия не списывается.'),13,20);}
if(id===158){progress(body,2);title(body,L('Keep control of risk','Контролируйте риск'),L('Set limits before the first copied action.','Задайте лимиты до первого копирования.'));const settings=[['Per position','На одну позицию','$20','Limits exposure to one market.','Лимит на один рынок.'],['New buys per day','Новые покупки в день','$30','Resets daily in your time zone.','Сброс в вашем часовом поясе.'],['Maximum signal age','Давность сигнала','30 sec','Older signals are skipped.','Старые сигналы пропускаются.']];for(const [en,rus,value,suben,subru] of settings){const g=card(body,'Risk / '+en,342,16,10);const r=row(g,'Label and switch',310,12);text(r,L(en,rus),15,21,'color/text/primary','Medium',246);const inst=tr(C.SwitchOn.createInstance());r.appendChild(inst);const valrow=row(g,'Limit',310,12);text(valrow,value==='30 sec'?L('30 sec','30 сек'):value,22,28,'color/text/primary','Semi Bold',76);text(valrow,L(suben,subru),12,18,'color/text/secondary','Regular',222);}text(body,L('You can change these limits later. They do not eliminate market risk.','Лимиты можно изменить позже. Они не устраняют рыночный риск.'),13,20);}
if(id===187){progress(body,3);title(body,L('Save your setup','Сохраните настройки'),L('Create an account to start and keep your demo session.','Создайте аккаунт для запуска и сохранения демо.'));for(const [en,rus,value] of [['Email','Email','you@example.com'],['Password','Пароль','••••••••••••']]){const g=auto(body,'Field / '+en,'VERTICAL',342,8);text(g,L(en,rus),14,20,'color/text/primary','Medium');const field=auto(g,'Input','HORIZONTAL',342,0,16,'color/bg/surface');field.resize(342,52);field.primaryAxisSizingMode='FIXED';field.counterAxisSizingMode='FIXED';field.counterAxisAlignItems='CENTER';rnd(field,'radius/md');field.strokes=[p('color/border/default')];text(field,value,15,20,'color/text/secondary','Regular',310);}text(body,L('This prototype shows the account step. No credentials are submitted.','Прототип показывает этап регистрации. Данные никуда не отправляются.'),13,20);notice(body,L('No wallet or payment is required for the demo.','Для демо не нужны кошелёк и оплата.'));}
if(id===210){progress(body,4);title(body,L('Ready to start','Всё готово к запуску'),L('Review your demo settings.','Проверьте настройки демо.'));const c=card(body,'Session summary');text(c,'0x7A…91F',22,28,'color/text/primary','Semi Bold');text(c,'Polymarket',13,20);kv(c,L('Virtual budget','Виртуальный бюджет'),'$200');kv(c,L('Per position','На одну позицию'),'$20');kv(c,L('Daily new buys','Покупки в день'),'$30');kv(c,L('Maximum signal age','Давность сигнала'),L('30 sec','30 сек'));text(c,L('Proportional copying within your limits.','Пропорциональное копирование в пределах лимитов.'),13,20);notice(body,L('Only virtual positions. Fees are shown for comparison and are not charged.','Только виртуальные позиции. Комиссии показаны для сравнения и не списываются.'));text(body,L('A positive demo result does not guarantee future returns.','Положительный результат демо не гарантирует доход в будущем.'),13,20);}
if(id===236){title(body,L('Your demo session','Ваша демо-сессия'),L('0x7A…91F · Day 3 of 7','0x7A…91F · День 3 из 7'));const c=card(body,'Session result');const r=row(c,'Result status');text(r,L('After virtual fees','После расчётных комиссий'),12,18,'color/text/secondary','Regular',210);badge(r,L('Active','Активна'),'Success');text(c,'+$18.40',34,40,'color/text/primary','Semi Bold');chart(c,84);const stats=row(c,'Session metrics',302,12);metric(stats,L('Budget used','Занято'),'$76 / $200',145);metric(stats,L('Copied / skipped','Скопировано / пропуск'),'12 / 2',145);const event=card(body,'Latest activity',342,16,8);const er=row(event,'Latest event',310);text(er,L('Latest activity','Последнее событие'),14,20,'color/text/primary','Medium',210);text(er,L('4 min ago','4 мин назад'),12,18,'color/text/secondary','Regular',88).textAlignHorizontal='RIGHT';text(event,L('Bought YES · $12.40','Покупка ДА · $12.40'),16,22,'color/text/primary','Medium');button(event,L('View activity','Все события'),prefix+':289','Quiet');}
if(id===289){title(body,L('Activity','События'),L('Every action and its confirmed status.','Каждое действие и его подтверждённый статус.'));for(const [status,titleEn,titleRu,descEn,descRu,tone] of [['Copied','Bought YES','Покупка ДА','$12.40 · Virtual fee $0.05','$12.40 · Расчёт комиссии $0.05','Success'],['Skipped','Signal too old','Сигнал устарел','46 sec delay · Limit 30 sec','Задержка 46 сек · Лимит 30 сек','Neutral'],['Checking','Waiting for confirmation','Ждём подтверждения','New risk is paused while we check.','Новый риск приостановлен до сверки.','Warning']]){const c=card(body,'Event / '+status,342,16,10);const rr=row(c,'Event metadata',310);badge(rr,L(status,status==='Copied'?'Скопировано':status==='Skipped'?'Пропущено':'Проверяется'),tone);text(rr,status==='Copied'?'12:45':status==='Skipped'?'12:43':'12:41',12,18,'color/text/secondary','Regular',74);text(c,L(titleEn,titleRu),17,24,'color/text/primary','Semi Bold');text(c,L(descEn,descRu),13,20);if(status==='Checking')button(c,L('View details','Подробнее'),prefix+':328','Secondary');}}
if(id===328){title(body,L('Checking the result','Проверяем результат'),L('Event #204 · Today, 12:41','Событие №204 · Сегодня, 12:41'));notice(body,L('New risk is paused. We are checking the outcome before changing your position.','Новый риск приостановлен. Сверяем результат перед изменением позиции.'),'warning');const c=card(body,'What happened');text(c,L('What happened','Что произошло'),17,24,'color/text/primary','Semi Bold');text(c,L('The venue has not confirmed the simulated action. The system will check its history automatically.','Площадка не подтвердила действие в симуляции. Система автоматически проверит историю.'),14,21);const timeline=auto(body,'Timeline','VERTICAL',342,16);for(const [time,en,russ] of [['12:41:03','Signal received','Сигнал получен'],['12:41:04','Risk checks passed','Лимиты проверены'],['12:41:11','Confirmation unavailable','Нет подтверждения'],['Now','Reconciliation in progress','Выполняется сверка']]){const rr=row(timeline,'Timeline row',342,16);text(rr,time==='Now'?L('Now','Сейчас'):time,12,18,'color/text/secondary','Medium',72);text(rr,L(en,russ),14,20,'color/text/primary','Regular',254);}text(body,L('No retry is needed. This event will update when the result is confirmed.','Повторять действие не нужно. Статус обновится после подтверждения.'),13,20);}
if(id===3)footer(s,L('Explore traders','Посмотреть трейдеров'),prefix+':31');
if(id===31)footer(s,L('Back to welcome','На главную'),prefix+':3');
if(id===90)footer(s,L('Try with a demo budget','Попробовать в демо'),prefix+':127',prefix+':31');
if(id===127)footer(s,L('Continue','Продолжить'),prefix+':158',prefix+':90');
if(id===158)footer(s,L('Save limits','Сохранить лимиты'),prefix+':187',prefix+':127');
if(id===187)footer(s,L('Continue in prototype','Продолжить в прототипе'),prefix+':210',prefix+':158');
if(id===210)footer(s,L('Start demo session','Запустить демо'),prefix+':236',prefix+':187');
if(id===236){button(s,L('Manage limits','Настроить лимиты'),prefix+':158','Secondary');nav(s,236);}
if(id===289)nav(s,289);
if(id===328)footer(s,L('Back to activity','Вернуться к событиям'),prefix+':289');
summaries.push({id:s.id,name:s.name,bodyHeight:body.height,contentBottom:body.children.length?Math.max(...body.children.map(n=>n.y+n.height)):0});}
for(const [node,destinationId]of links)await node.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[destinationId.startsWith('http')?{type:'URL',url:destinationId}:{type:'NODE',destinationId,navigation:'NAVIGATE',transition:{type:'DISSOLVE',easing:{type:'EASE_OUT'},duration:.18},resetScrollPosition:true}]}]);
return {createdNodeIds:created,removedNodeIds:removed,mutatedNodeIds:mutated,rollbackId:rollback.id,screens:summaries,linkedTargets:links.map(([n,d])=>({id:n.id,to:d}))};
