const p=await figma.getNodeByIdAsync('205:2');await figma.setCurrentPageAsync(p);
for(const s of ['Regular','Medium','Semi Bold','Bold'])await figma.loadFontAsync({family:'Inter',style:s});
figma.skipInvisibleInstanceChildren=false;const created=[],mutated=[],records=[];
const variables=await figma.variables.getLocalVariablesAsync(),vm=Object.fromEntries(variables.map(v=>[v.name,v]));
const styles=await figma.getLocalTextStylesAsync(),sm=Object.fromEntries(styles.map(s=>[s.name,s]));
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',vm[k]);
function box(parent,name,w,dir='VERTICAL',gap=16,padding=0,bg=null){const n=figma.createAutoLayout(dir);parent.appendChild(n);n.name=name;n.resize(w,10);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='HUG';n.itemSpacing=gap;n.paddingTop=n.paddingBottom=n.paddingLeft=n.paddingRight=padding;n.fills=bg?[paint(bg)]:[];if(bg){n.cornerRadius=14;n.setBoundVariable('cornerRadius',vm['radius/lg']);n.strokes=[paint('color/border/default')];}created.push(n.id);return n;}
function text(parent,name,value,w,style='Body/Small',tone='color/text/primary'){const t=figma.createText();parent.appendChild(t);t.name=name;t.fontName=sm[style].fontName;t.textStyleId=sm[style].id;t.characters=value;t.fills=[paint(tone)];t.textAutoResize='HEIGHT';t.resize(w,Math.max(20,t.height));created.push(t.id);return t;}
async function button(parent,label,w,source,primary=false){const m=await figma.getNodeByIdAsync(primary?'113:240':'113:242'),n=m.createInstance();parent.appendChild(n);n.name='Button/'+label;n.resize(w,48);for(const t of n.findAllWithCriteria({types:['TEXT']})){t.characters=label;created.push(t.id);}created.push(n.id);if(source){await n.setReactionsAsync(source.reactions);mutated.push(n.id);}return n;}
function labelOf(n){return n.type==='INSTANCE'?n.findAllWithCriteria({types:['TEXT']}).map(t=>t.characters).join(' '):n.name.replace(/^Action \/ /,'');}
async function nav(n,id){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:false}]}]);mutated.push(n.id);}
async function prepare(id,title,subtitle){const root=await figma.getNodeByIdAsync(id);if(root.children.some(n=>n.name==='Recovery content / approved'))return null;
const actionNodes=root.findAll(n=>'reactions'in n&&n.reactions.length),actions={};for(const n of actionNodes)actions[labelOf(n)]=n;
const legacy=root.children.map(n=>n.id);for(const n of [...root.children]){n.visible=false;mutated.push(n.id);}
const wrap=figma.createFrame();root.appendChild(wrap);wrap.name='Recovery content / approved';wrap.resize(1440,960);wrap.layoutPositioning='ABSOLUTE';wrap.x=0;wrap.y=0;wrap.fills=[];created.push(wrap.id);
const source=await figma.getNodeByIdAsync('1015:3835');for(const child of source.children.filter(n=>n.name!=='Scroll viewport')){const c=child.clone();wrap.appendChild(c);c.x=child.x;c.y=child.y;created.push(c.id,...c.findAll(()=>true).map(n=>n.id));
if(c.name==='App shell / Sidebar'){for(const item of c.findAll(n=>n.name.startsWith('Nav/'))){const old=actions[labelOf(item)];if(old){function clean(a){if(a.type==='NODE'&&a.navigation==='SCROLL_TO')return null;if(a.type==='CONDITIONAL')a.conditionalBlocks=a.conditionalBlocks.map(b=>({...b,actions:b.actions.map(clean).filter(Boolean)}));return a;}await item.setReactionsAsync(JSON.parse(JSON.stringify(old.reactions)).map(r=>({trigger:r.trigger,actions:(r.actions||[r.action]).map(clean).filter(Boolean)})));mutated.push(item.id);}if(item.name==='Nav/home'){const master=await figma.getNodeByIdAsync('1013:34');item.swapComponent(master);mutated.push(item.id);}}}
if(c.type==='INSTANCE'&&c.name==='Recovery/Header'){for(const t of c.findAllWithCriteria({types:['TEXT']})){if(t.name==='Главная')t.characters=title;if(t.name==='Your paper session is active and rec')t.characters=subtitle;if(t.name==='Available balance')t.setBoundVariable('characters',await figma.variables.getVariableByIdAsync('VariableID:830:4'));mutated.push(t.id);}for(const n of c.findAll(n=>'reactions'in n&&n.reactions.length)){const dest=n.name.includes('Balance')?'905:9228':n.name.includes('Notifications')?'905:9272':n.name.includes('Profile')?'905:9338':null;if(dest&&dest!==id)await nav(n,dest);else if(dest===id){await n.setReactionsAsync([]);mutated.push(n.id);}}}}
const view=box(wrap,'Scroll viewport',1152,'VERTICAL',0);view.resize(1152,832);view.primaryAxisSizingMode='FIXED';view.layoutSizingVertical='FIXED';view.x=256;view.y=104;view.clipsContent=true;view.overflowDirection='VERTICAL';const content=box(view,'Page content',1152,'VERTICAL',24);content.paddingBottom=24;
root.name='Current / '+title+' / desktop RU';root.resize(1440,960);mutated.push(root.id);records.push({rootId:id,preservedChildren:legacy});return{root,content,actions};}

const frames={"home":"905:9074","catalog":"905:9096","catalog-filter":"905:9118","search":"905:9140","positions":"905:9162","orders":"905:9184","events":"905:9206","funds":"905:9228","operations":"905:9250","notifications":"905:9272","tickets":"905:9294","help":"905:9316","profile":"905:9338","report":"905:9360","entry":"905:9382","future":"905:9404","draft":"905:9426","sent":"905:9448","detail-position":"905:9470","detail-order":"905:9492","detail-event":"905:9514","detail-operation":"905:9536","detail-ticket":"905:9558","detail-faq":"905:9580","trader-24h":"905:9602","trader-7d":"905:9624","trader-30d":"905:9646","trader-90d":"905:9668","thread":"905:9690","welcome":"949:12977","before":"949:13017","setup":"949:13057","setup-review":"949:13097","launch":"949:13137","fresh":"949:13177","history":"949:13217","markets":"949:13257","catalog-sort":"950:16776","trader-all":"950:16816","order-cancel":"951:13662","order-change":"951:13702","order-requested":"951:13742","position-manual":"951:13782","position-close":"951:13822","position-requested":"951:13862","label":"951:13902","venue-account":"951:13942","fresh-funds":"955:3652","fresh-positions":"955:3698","fresh-events":"955:3744","onboarding":"955:3790","global-risk":"965:18276","custom-risk":"965:18321"};
const titles={'catalog-filter':'Фильтры трейдеров',search:'Поиск трейдера',help:'Центр помощи',report:'Отчёт',future:'Реальные счета',draft:'Новое обращение',sent:'Обращение отправлено','detail-faq':'Ответ на вопрос','trader-24h':'Профиль трейдера','trader-7d':'Профиль трейдера','trader-30d':'Профиль трейдера','trader-90d':'Профиль трейдера','trader-all':'Профиль трейдера',thread:'Переписка',welcome:'С возвращением',before:'Начните копирование',setup:'Настройка копирования','setup-review':'Проверка настроек',launch:'Запуск копирования',fresh:'Главная',history:'История копирования',markets:'Рынки','order-cancel':'Отмена заявки','order-change':'Изменение заявки','order-requested':'Запрос отправлен','position-manual':'Самостоятельное управление','position-close':'Закрытие позиции','position-requested':'Запрос отправлен',label:'Моя метка','venue-account':'Счёт площадки','fresh-funds':'Средства','fresh-positions':'Позиции','fresh-events':'События',onboarding:'Как работает копирование','global-risk':'Общие правила риска','custom-risk':'Риски трейдера'};
for(const [key,id]of Object.entries(frames)){if(key==='entry')continue;const root=await figma.getNodeByIdAsync(id);if(root.children.some(n=>n.name==='Recovery content / approved'))continue;const source=root.findAllWithCriteria({types:['FRAME']}).find(n=>n.name.startsWith('Scroll content'));if(!source)continue;const children=[...source.children];const out=await prepare(id,titles[key]||root.name.split('/')[1],'');if(!out)continue;
const cols=box(out.content,'Workspace columns',1152,'HORIZONTAL',24),left=box(cols,'Primary content',744),right=box(cols,'Supporting actions',384);const identity=box(left,'Page summary',744,'VERTICAL',12,24,'color/bg/surface'),actions=box(right,'Actions',384,'VERTICAL',12,24,'color/bg/surface');text(actions,'Title','Действия',336,'Heading/Small');let group=identity,toolbar=null;
for(const c of children){
if(c.type==='TEXT'){if(c.name==='Scroll anchor'){out.content.insertChild(0,c);mutated.push(c.id);continue;}if(['Synthetic scope','Prepared search','Recommended budget'].includes(c.name)){c.visible=false;mutated.push(c.id);continue;}if(c.name==='Filter label'||/Limit label/.test(c.name)){group=box(left,'Field group/'+c.characters,744,'VERTICAL',12,24,'color/bg/surface');toolbar=null;}
group.appendChild(c);c.resize(696,c.height);c.textAutoResize='HEIGHT';c.textStyleId=sm[/name|title/i.test(c.name)?'Heading/Medium':c.name==='Filter label'?'Label':'Body/Small'].id;mutated.push(c.id);
}else if(c.type==='INSTANCE'&&/Action|configure/.test(c.name)){if(/За всё время/.test(c.name)){if(!toolbar)toolbar=box(group,'Period control',696,'HORIZONTAL',8);toolbar.appendChild(c);c.resize(128,48);}else{actions.appendChild(c);c.resize(336,48);}mutated.push(c.id);
}else if(c.type==='FRAME'&&/Toolbar|toolbar/.test(c.name)){if(!toolbar)toolbar=box(group,'Controls',696,'HORIZONTAL',8);toolbar.layoutWrap='WRAP';for(const item of [...c.children]){toolbar.appendChild(item);if(item.type==='INSTANCE')item.resize(160,48);mutated.push(item.id);}}
else if(c.type==='INSTANCE'&&c.name.startsWith('Item /')){left.appendChild(c);c.resize(744,c.height);for(const t of c.findAllWithCriteria({types:['TEXT']})){if(t.name==='Note')t.visible=false;mutated.push(t.id);}mutated.push(c.id);}
else{left.appendChild(c);c.resize(744,c.height);if(c.type==='FRAME'&&c.layoutMode!=='NONE'){c.paddingLeft=c.paddingRight=c.paddingTop=c.paddingBottom=24;c.itemSpacing=12;for(const t of c.findAllWithCriteria({types:['TEXT']})){t.resize(696,t.height);t.textAutoResize='HEIGHT';t.textStyleId=sm[t.name==='Card title'?'Heading/Small':'Body/Small'].id;mutated.push(t.id);}}mutated.push(c.id);}
}
if(identity.children.length===0)identity.visible=false;if(actions.children.length===1)actions.visible=false;
if(['fresh','before','welcome','fresh-funds','fresh-positions','fresh-events','onboarding'].includes(key)){for(const t of out.root.children.find(n=>n.name==='Recovery content / approved').findAllWithCriteria({types:['TEXT']})){if(t.name==='Available balance'){t.setBoundVariable('characters',null);t.characters='200,00 $';mutated.push(t.id);}}}
}
return{createdNodeIds:created,mutatedNodeIds:mutated,records};
