const p=await figma.getNodeByIdAsync('205:2');await figma.setCurrentPageAsync(p);
for(const s of ['Regular','Medium','Semi Bold','Bold'])await figma.loadFontAsync({family:'Inter',style:s});
figma.skipInvisibleInstanceChildren=false;const created=[],mutated=[],records=[];
const variables=await figma.variables.getLocalVariablesAsync(),vm=Object.fromEntries(variables.map(v=>[v.name,v]));
const styles=await figma.getLocalTextStylesAsync(),sm=Object.fromEntries(styles.map(s=>[s.name,s]));
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',vm[k]);
function box(parent,name,w,dir='VERTICAL',gap=16,padding=0,bg=null){const n=figma.createAutoLayout(dir);parent.appendChild(n);n.name=name;n.resize(w,10);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='HUG';n.itemSpacing=gap;n.paddingTop=n.paddingBottom=n.paddingLeft=n.paddingRight=padding;n.fills=bg?[paint(bg)]:[];if(bg){n.cornerRadius=14;n.setBoundVariable('cornerRadius',vm['radius/lg']);n.strokes=[paint('color/border/default')];}created.push(n.id);return n;}
function text(parent,name,value,w,style='Body/Small',tone='color/text/primary'){const t=figma.createText();parent.appendChild(t);t.name=name;t.fontName=sm[style].fontName;t.textStyleId=sm[style].id;t.characters=value;t.fills=[paint(tone)];t.textAutoResize='HEIGHT';t.resize(w,Math.max(20,t.height));created.push(t.id);return t;}
async function button(parent,label,w,source,primary=false){const m=await figma.getNodeByIdAsync(primary?'113:240':'113:242'),n=m.createInstance();parent.appendChild(n);n.name='Button/'+label;n.resize(w,48);for(const t of n.findAllWithCriteria({types:['TEXT']})){t.characters=label;created.push(t.id);}created.push(n.id);if(source){await n.setReactionsAsync(source.reactions);mutated.push(n.id);}return n;}
function labelOf(n){return n.type==='INSTANCE'?n.findAllWithCriteria({types:['TEXT']}).map(t=>t.characters).join(' '):n.name.replace(/^Action \/ /,'');}
async function nav(n,id){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:false}]}]);mutated.push(n.id);}
async function prepare(id,title,subtitle){const root=await figma.getNodeByIdAsync(id);if(root.children.some(n=>n.name==='Recovery content / approved'))return null;
const actionNodes=root.findAll(n=>'reactions'in n&&n.reactions.length),actions={};for(const n of actionNodes)actions[labelOf(n)]=n;
const legacy=root.children.map(n=>n.id);for(const n of [...root.children]){n.visible=false;mutated.push(n.id);}
const wrap=figma.createFrame();root.appendChild(wrap);wrap.name='Recovery content / approved';wrap.resize(1440,960);wrap.layoutPositioning='ABSOLUTE';wrap.x=0;wrap.y=0;wrap.fills=[];created.push(wrap.id);
const source=await figma.getNodeByIdAsync('1015:3835');for(const child of source.children.filter(n=>n.name!=='Scroll viewport')){const c=child.clone();wrap.appendChild(c);c.x=child.x;c.y=child.y;created.push(c.id,...c.findAll(()=>true).map(n=>n.id));
if(c.name==='App shell / Sidebar'){for(const item of c.findAll(n=>n.name.startsWith('Nav/'))){const old=actions[labelOf(item)];if(old){await item.setReactionsAsync(old.reactions);mutated.push(item.id);}if(item.name==='Nav/home'){const master=await figma.getNodeByIdAsync('1013:34');item.swapComponent(master);mutated.push(item.id);}}}
if(c.type==='INSTANCE'&&c.name==='Recovery/Header'){for(const t of c.findAllWithCriteria({types:['TEXT']})){if(t.name==='Главная')t.characters=title;if(t.name==='Your paper session is active and rec')t.characters=subtitle;if(t.name==='Available balance')t.setBoundVariable('characters',await figma.variables.getVariableByIdAsync('VariableID:830:4'));mutated.push(t.id);}for(const n of c.findAll(n=>'reactions'in n&&n.reactions.length)){const dest=n.name.includes('Balance')?'905:9228':n.name.includes('Notifications')?'905:9272':n.name.includes('Profile')?'905:9338':null;if(dest&&dest!==id)await nav(n,dest);else if(dest===id){await n.setReactionsAsync([]);mutated.push(n.id);}}}}
const view=box(wrap,'Scroll viewport',1152,'VERTICAL',0);view.resize(1152,832);view.primaryAxisSizingMode='FIXED';view.layoutSizingVertical='FIXED';view.x=256;view.y=104;view.clipsContent=true;view.overflowDirection='VERTICAL';const content=box(view,'Page content',1152,'VERTICAL',24);content.paddingBottom=24;
root.name='Current / '+title+' / desktop RU';root.resize(1440,960);mutated.push(root.id);records.push({rootId:id,preservedChildren:legacy});return{root,content,actions};}

for(const [id,title,subtitle]of [['905:9470','Деталь позиции','Стоимость, результат и управление позицией'],['905:9492','Деталь заявки','Состояние исполнения и доступные действия'],['905:9514','Деталь события','Причина и связанные записи'],['905:9536','Операция','Изменение средств вашего счёта'],['905:9558','Обращение','Статус и контекст обращения']]){
const root=await figma.getNodeByIdAsync(id),source=root.findAllWithCriteria({types:['FRAME']}).find(n=>n.name.startsWith('Scroll content'));if(!source)continue;const children=[...source.children],out=await prepare(id,title,subtitle);if(!out)continue;
const cols=box(out.content,'Detail columns',1152,'HORIZONTAL',24),left=box(cols,'Record details',744),right=box(cols,'Record actions',384);const summary=box(left,'Record summary',744,'VERTICAL',12,24,'color/bg/surface'),details=box(left,'Record data',744,'VERTICAL',16,24,'color/bg/surface');text(details,'Section heading','Подробности',696,'Heading/Small');
const actions=box(right,'Actions',384,'VERTICAL',12,24,'color/bg/surface');text(actions,'Heading','Действия',336,'Heading/Small');
for(const c of children){if(c.type==='TEXT'){if(c.name==='Scroll anchor'){out.content.insertChild(0,c);mutated.push(c.id);continue;}const parent=c.name==='Object body'?details:c.name==='Object ID'?details:summary;parent.appendChild(c);c.resize(696,c.height);c.textAutoResize='HEIGHT';c.textStyleId=sm[c.name==='Object title'?'Heading/Medium':c.name==='Object value'?'Heading/Small':'Body/Small'].id;mutated.push(c.id);}else if(c.type==='INSTANCE'&&c.name.startsWith('Action /')){actions.appendChild(c);c.resize(336,48);mutated.push(c.id);for(const t of c.findAllWithCriteria({types:['TEXT']})){t.characters=t.characters.replace('Связанная запись: Деталь заявки','Связанная заявка').replace('Связанная запись: Деталь позиции','Связанная позиция').replace('Связанная запись: Деталь события','Связанное событие');mutated.push(t.id);}}else{left.appendChild(c);c.resize(744,c.height);mutated.push(c.id);}}
}
return{createdNodeIds:created,mutatedNodeIds:mutated,records};
