const page = await figma.getNodeByIdAsync(CFG.pageId);
await figma.setCurrentPageAsync(page);
for (const style of ['Regular','Medium','Semi Bold','Bold']) await figma.loadFontAsync({family:'Inter',style});
const created=[]; const mutated=[];
const track=n=>{created.push(n.id);return n;};
const vars=await figma.variables.getLocalVariablesAsync();
const vm=Object.fromEntries(vars.map(v=>[v.name,v]));
const styles=await figma.getLocalTextStylesAsync();const sm=Object.fromEntries(styles.map(s=>[s.name,s]));
function paint(name){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',vm[name]);}
function color(n,name){n.fills=[paint(name)];}
function gap(n,value){n.itemSpacing=value;const v=vars.find(v=>v.name.startsWith('spacing/')&&Object.values(v.valuesByMode).includes(value));if(v)n.setBoundVariable('itemSpacing',v);}
function pad(n,value){for(const k of ['paddingTop','paddingBottom','paddingLeft','paddingRight']){n[k]=value;const v=vars.find(v=>v.name.startsWith('spacing/')&&Object.values(v.valuesByMode).includes(value));if(v)n.setBoundVariable(k,v);}}
function box(parent,name,w,dir='VERTICAL',spacing=16,bg=null,padding=0){const n=track(figma.createAutoLayout(dir));parent.appendChild(n);n.name=name;n.resize(w,10);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.layoutSizingVertical='HUG';n.fills=[];gap(n,spacing);pad(n,padding);if(bg){color(n,bg);n.cornerRadius=14;n.setBoundVariable('cornerRadius',vm['radius/lg']);n.strokes=[paint('color/border/default')];n.strokeWeight=1;}return n;}
function text(parent,name,value,style='Body/Small',tone='color/text/primary',width){const t=track(figma.createText());parent.appendChild(t);t.name=name;t.fontName=sm[style].fontName;t.textStyleId=sm[style].id;t.characters=value;color(t,tone);t.textAutoResize='HEIGHT';t.resize(width||Math.max(20,parent.width-parent.paddingLeft-parent.paddingRight),t.height);return t;}
function icon(parent,name,size=20){const svg=CFG.icons[name];if(!svg)return null;const n=track(figma.createNodeFromSvg(svg.replace(/currentColor/g,'#A3ADC2')));parent.appendChild(n);n.name='Icon/'+name;n.resize(size,size);for(const v of n.findAllWithCriteria({types:['VECTOR']})){created.push(v.id);if(v.strokes.length)v.strokes=v.strokes.map(p=>p.type==='SOLID'?paint('color/text/secondary'):p);if(v.fills.length)v.fills=v.fills.map(p=>p.type==='SOLID'?paint('color/text/secondary'):p);}return n;}
function expose(comp){for(const t of comp.findAllWithCriteria({types:['TEXT']})){const key=comp.addComponentProperty(t.name,'TEXT',t.characters);t.componentPropertyReferences={characters:key};}comp.description='Recovery reference component. Semantic role and token bindings preserved; use in review screens before rollout.';}
function props(inst,values){const out={};for(const [name,val] of Object.entries(values)){const k=Object.keys(inst.componentProperties).find(k=>k.split('#')[0]===name);if(k)out[k]=val;}inst.setProperties(out);for(const t of inst.findAllWithCriteria({types:['TEXT']})){if(Object.prototype.hasOwnProperty.call(values,t.name)){t.characters=values[t.name];created.push(t.id);}}}
function instance(parent,comp,name,width,values={}){const n=track(comp.createInstance());parent.appendChild(n);n.name=name;if(width)n.resize(width,n.height);n.layoutSizingVertical='HUG';props(n,values);return n;}
async function button(parent,label,width=160,primary=false){const comp=await figma.getNodeByIdAsync(primary?'113:240':'113:242');const n=track(comp.createInstance());parent.appendChild(n);n.name='Button/'+label;n.resize(width,48);for(const t of n.findAllWithCriteria({types:['TEXT']})){t.characters=label;created.push(t.id);}return n;}
async function nav(n,destination,navigation='NAVIGATE',extra=[]){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[...extra,{type:'NODE',destinationId:destination,navigation,transition:null,resetScrollPosition:false}]}]);mutated.push(n.id);}
function flex(t){t.layoutSizingHorizontal='FILL';}
function money(v,signed=false){if(v==null)return CFG.en?'No data':'Нет данных';let x=(Math.abs(v)/100).toFixed(2);if(!CFG.en)x=x.replace('.',',');return (v<0?'−':signed&&v>0?'+':'')+(CFG.en?'$'+x:x+' $');}
const en=CFG.en;const L=(ru,enText)=>en?enText:ru;const desktop=CFG.desktop;const W=desktop?1440:390,H=desktop?960:844,inner=desktop?1152:350;
const section=page;
const comps={};for(const [k,id] of Object.entries(CFG.components))comps[k]=await figma.getNodeByIdAsync(id);
const destinations=CFG.destinations;
const legacyRoots={};
function root(name,x){const id=name.startsWith('Home')?CFG.existingHome:CFG.existingCatalog;const f=sourceRoots[id];if(f.children.some(n=>n.name==='Recovery/Header'))throw new Error('Scoped recovery already exists '+id);const old=track(figma.createFrame());f.appendChild(old);old.name='Legacy / preserved inbound IDs';old.visible=false;old.resize(390,844);legacyRoots[id]=old;for(const n of [...f.children])if(n!==old)old.appendChild(n);f.layoutMode='NONE';f.resize(W,H);f.clipsContent=true;mutated.push(f.id);return f;}
const sourceRoots={};for(const id of [CFG.existingHome,CFG.existingCatalog])sourceRoots[id]=await figma.getNodeByIdAsync(id);const home=root(L('Главная · активное демо','Home · active demo'),40);const catalogue=root(L('Трейдеры','Traders'),desktop?1560:480);
const pending=[];
async function shell(f,which){
 if(desktop){const side=box(f,'App shell / Sidebar',224,'VERTICAL',8,'color/bg/surface',20);side.resize(224,H);side.primaryAxisSizingMode='FIXED';side.cornerRadius=0;side.x=0;side.y=0;
 text(side,'Brand','shadow','Brand','color/text/primary',184);const spacer=box(side,'Brand spacing',184,'VERTICAL',0);spacer.resize(184,20);spacer.primaryAxisSizingMode='FIXED';
 for(const [role,label,ic] of [['home',L('Главная','Home'),'house'],['catalogue',L('Трейдеры','Traders'),'users'],['positions',L('Позиции','Positions'),'layers'],['events',L('События','Events'),'activity']]){const n=instance(side,role===which?(comps['navSelected'+role]||comps.navSelected):(comps['navDefault'+role]||comps.navDefault),'Nav/'+role,184,{Label:label});pending.push({n,target:role});}
 const space=box(side,'Flexible spacer',184,'VERTICAL',0);space.layoutSizingVertical='FILL';const help=instance(side,comps.navDefault,'Nav/help',184,{Label:L('Помощь','Help')});pending.push({n:help,target:'help'});
 const h=track((await figma.getNodeByIdAsync('819:330')).createInstance());f.appendChild(h);h.name='Recovery/Header';h.resize(inner,68);h.x=256;h.y=24;props(h,{'Text 1':which==='home'?L('Главная','Home'):L('Трейдеры','Traders'),'Balance context':which==='home'?L('Ваше копирование и позиции','Your copying and positions'):L('Выберите трейдера для копирования','Choose a trader to copy'),'Balance context 3':L('Демо · доступно','Demo · available'),'Balance value':money(18038)});for(const t of h.findAllWithCriteria({types:['TEXT']}))if(t.boundVariables.characters)t.setBoundVariable('characters',null);
 for(const n of h.findAllWithCriteria({types:['FRAME']})){if(n.name==='Balance / Open wallets')pending.push({n,target:'funds'});if(n.name==='Button/Notifications')pending.push({n,target:'notifications'});if(n.name==='Button/Profile avatar')pending.push({n,target:'profile'});}
 }else{const h=track((await figma.getNodeByIdAsync('819:294')).createInstance());f.appendChild(h);h.name='Recovery/Header';h.resize(350,44);h.x=20;h.y=20;props(h,{'Brand':'shadow','Balance context':L('Демо · доступно','Demo · available'),'Balance value':money(18038)});for(const t of h.findAllWithCriteria({types:['TEXT']}))if(t.boundVariables.characters)t.setBoundVariable('characters',null);for(const n of h.findAllWithCriteria({types:['FRAME']})){if(n.name==='Balance / Open wallets')pending.push({n,target:'funds'});if(n.name==='Button/Notifications')pending.push({n,target:'notifications'});if(n.name==='Profile / Open account')pending.push({n,target:'profile'});}
 const bottom=box(f,'App shell / Bottom navigation',350,'HORIZONTAL',0,'color/bg/surface',0);bottom.resize(350,64);bottom.primaryAxisSizingMode='FIXED';bottom.x=20;bottom.y=760;
 for(const [role,label,ic] of [['home',L('Главная','Home'),'house'],['catalogue',L('Трейдеры','Traders'),'users'],['positions',L('Позиции','Positions'),'layers'],['events',L('События','Events'),'activity']]){const item=box(bottom,'Nav/'+role,87.5,'VERTICAL',4,role===which?'color/accent/subtle':null,8);item.resize(87.5,64);item.primaryAxisSizingMode='FIXED';item.counterAxisAlignItems='CENTER';icon(item,ic);const t=text(item,'Label',label,'Caption',role===which?'color/accent/text':'color/text/secondary',71.5);t.textAlignHorizontal='CENTER';pending.push({n:item,target:role});}
 }
 const viewport=box(f,'Scroll viewport',inner,'VERTICAL',0);viewport.resize(inner,desktop?832:664);viewport.primaryAxisSizingMode='FIXED';viewport.clipsContent=true;viewport.overflowDirection='VERTICAL';viewport.x=desktop?256:20;viewport.y=desktop?104:80;
 const content=box(viewport,'Page content',inner,'VERTICAL',desktop?24:16);content.paddingBottom=24;
 if(!desktop)text(content,'Page title',which==='home'?L('Главная','Home'):L('Трейдеры','Traders'),'Heading/Large');return content;
}
const hc=await shell(home,'home');const cc=await shell(catalogue,'catalogue');
if(desktop){const row=box(hc,'Account overview',inner,'HORIZONTAL',16);for(const [label,value,hint] of [[L('Стоимость демо-счёта','Demo account value'),money(20977),L('Результат +9,77 $','Result +$9.77')],[L('Доступно','Available'),money(18038),L('Для новых покупок','For new purchases')],[L('В позициях','In positions'),money(2360),L('5 текущих позиций','5 current positions')],[L('В резерве','Reserved'),money(579),L('Ожидающие заявки','Pending orders')]]){const m=instance(row,comps.metric,'Account metric',276,{Label:label,Value:value,Hint:hint});pending.push({n:m,target:'funds'});}}
else{const b=box(hc,'Demo account',350,'VERTICAL',8,'color/bg/surface',16);text(b,'Label',L('Стоимость демо-счёта','Demo account value'),'Body/Small','color/text/secondary');text(b,'Value',money(20977),'Numeric/Large');text(b,'Result',L('Результат копирования ','Copy result ')+money(977,true),'Body/Small medium','color/success/text');for(const [label,value] of [[L('Доступно','Available'),18038],[L('В резерве','Reserved'),579],[L('В позициях','In positions'),2360]]){const r=box(b,'Money row',318,'HORIZONTAL',8);text(r,'Label',label,'Body/Small','color/text/secondary',190);const t=text(r,'Amount',money(value),'Numeric/Small','color/text/primary',120);t.textAlignHorizontal='RIGHT';}pending.push({n:b,target:'funds'});}
let main=hc,right=null;if(desktop){const row=box(hc,'Workspace columns',inner,'HORIZONTAL',24);main=box(row,'Primary column',744);right=box(row,'Secondary column',384);}
const session=box(main,'Copy session',desktop?744:350,'VERTICAL',16,'color/bg/surface',desktop?24:16);text(session,'Heading',L('Копирование','Copying'),'Heading/Compact');const idrow=box(session,'Trader identity',session.width-2*session.paddingLeft,'HORIZONTAL',12);const names=box(idrow,'Identity',desktop?470:200,'VERTICAL',4);text(names,'Name','Momentum Fox','Heading/Small');text(names,'Venue','Polymarket','Body/Small','color/text/secondary');text(idrow,'Status',L('Активно','Active'),'Label','color/success/text',100);
text(session,'Result',money(977,true),'Numeric/Large','color/success/text');text(session,'Result breakdown',L('Реализовано +1,22 $ · Текущая оценка +8,55 $','Realized +$1.22 · Unrealized +$8.55'),'Body/Small','color/text/secondary');text(session,'Limits',L('На позицию 20 $ · Новые покупки 30 $ в день','Per position $20 · New purchases $30/day'),'Body/Small','color/text/secondary');const open=await button(session,L('Открыть копирование','Open copying'),desktop?224:318,true);pending.push({n:open,target:'copy'});
const positions=box(main,'Current positions',desktop?744:350,'VERTICAL',12,'color/bg/surface',desktop?24:16);const ph=box(positions,'Section heading',positions.width-2*positions.paddingLeft,'HORIZONTAL',8);const title=text(ph,'Heading',L('Текущие позиции · 5','Current positions · 5'),'Heading/Small',undefined,desktop?500:218);const all=await button(ph,L('Все','View all'),desktop?100:92);pending.push({n:all,target:'positions'});
for(const p of CFG.positions){const r=box(positions,'Position/'+p.id,positions.width-2*positions.paddingLeft,'HORIZONTAL',12);const col=box(r,'Market',desktop?490:192,'VERTICAL',4);text(col,'Market name',en?p.market:p.marketRu,'Body/Small medium');text(col,'Status',en?p.statusEn:p.statusRu,'Caption/Regular','color/text/secondary');const amounts=box(r,'Amounts',desktop?180:114,'VERTICAL',4);const v=text(amounts,'Value',money(p.markValueCents),'Numeric/Small');v.textAlignHorizontal='RIGHT';const pnl=text(amounts,'PnL',money(p.pnl,true),'Body/Small',p.pnl>=0?'color/success/text':'color/danger/text');pnl.textAlignHorizontal='RIGHT';pending.push({n:r,target:'positions'});}
const aside=right||hc;const attention=box(aside,'Attention',desktop?384:350,'VERTICAL',12,'color/warning/bg',16);text(attention,'Heading',L('Исход заявки уточняется','Order outcome is being checked'),'Heading/Small','color/warning/text');text(attention,'Explanation',L('Проверяем исполнение. Резерв сохраняется до подтверждения.','Execution is being checked. Funds remain reserved until confirmed.'),'Body/Small');const inspect=await button(attention,L('Посмотреть заявку','View order'),desktop?224:318);pending.push({n:inspect,target:'unknown'});
const events=box(aside,'Recent events',desktop?384:350,'VERTICAL',16,'color/bg/surface',16);text(events,'Heading',L('Последние события','Recent events'),'Heading/Small');for(const e of CFG.events){const row=box(events,'Event/'+e.id,events.width-32,'VERTICAL',4);text(row,'Event title',en?e.en:e.ru,'Body/Small medium');text(row,'Event meta',e.time+' · '+(en?e.statusEn:e.statusRu),'Caption/Regular','color/text/secondary');pending.push({n:row,target:'events'});}const ea=await button(events,L('Все события','All events'),desktop?200:318);pending.push({n:ea,target:'events'});
const toolbar=box(cc,'Catalogue toolbar',inner,desktop?'HORIZONTAL':'VERTICAL',12);const search=instance(toolbar,comps.search,'Input/Search',desktop?668:350,{Placeholder:L('Имя или адрес трейдера','Trader name or address')});const controlrow=desktop?toolbar:box(toolbar,'Filter and sort',350,'HORIZONTAL',12);const filters=await button(controlrow,L('Фильтры','Filters'),desktop?160:132);const sort=await button(controlrow,L('По PnL ▾','By PnL ▾'),desktop?300:206);
const chips=box(cc,'Collections',inner,'HORIZONTAL',12);const positive=await button(chips,L('PnL > 0','PnL > 0'),desktop?144:132);const budget=await button(chips,L('Бюджет до 50 $','Budget ≤ $50'),desktop?196:206);const count=text(cc,'Result count',L('24 трейдера · 30 дней','24 traders · 30 days'),'Body/Small','color/text/secondary');
const list=box(cc,'Trader grid',inner,'VERTICAL',16);const traderNodes=[];let gridrow;
for(let i=0;i<CFG.traders.length;i++){const t=CFG.traders[i];if(desktop&&i%3===0)gridrow=box(list,'Grid row '+Math.floor(i/3),inner,'HORIZONTAL',16);const n=instance(desktop?gridrow:list,comps.trader,'Trader/'+t.id,desktop?373.33:350,{Initials:t.name.split(' ').map(x=>x[0]).join(''),Name:t.name,Venue:t.venue==='polymarket'?'Polymarket':'Limitless',PnlLabel:L('PnL · 30 дней','PnL · 30 days'),PnlValue:money(t.publicPnlCents,true),DrawdownLabel:L('Макс. просадка','Max drawdown'),DrawdownValue:t.drawdownBasisPoints==null?'—':(t.drawdownBasisPoints/100).toFixed(2).replace('.',en?'.':',')+'%',Budget:L('От ','From ')+money(t.minimumBudgetCents),History:t.historyDays<30?L('История < 30 дней','History < 30 days'):L('История ','History ')+t.historyDays+L(' дней',' days')});const v=n.findAllWithCriteria({types:['TEXT']}).find(x=>x.name==='PnlValue');if(v)color(v,t.publicPnlCents==null?'color/text/secondary':t.publicPnlCents>=0?'color/success/text':'color/danger/text');traderNodes.push({n,t});}
// Retain the existing record initialization and detail destination for each trader.
const source=legacyRoots[CFG.existingCatalog];
for(const {n,t} of traderNodes){const old=source.findAllWithCriteria({types:['INSTANCE']}).find(x=>x.name.includes('trader / '+t.id));if(old){await n.setReactionsAsync(old.reactions);mutated.push(n.id);}}

for(const f of [home,catalogue]){
 const old=legacyRoots[f.id];const newHeader=f.findOne(n=>n.name==='Recovery/Header');const oldHeader=old.findOne(n=>n.name==='Shared header / explorer');
 for(const t of newHeader.findAllWithCriteria({types:['TEXT']}))if(t.name==='Нет данных')t.setBoundVariable('characters',vm['Review/BalanceEN']);
 for(const name of ['Balance / Open wallets','Button/Notifications','Profile / Open account']){const n=newHeader.findOne(n=>n.name===name),o=oldHeader.findOne(n=>n.name===name);if(n&&o)await n.setReactionsAsync(o.reactions);}
 const oldNav=old.findOne(n=>n.name==='Shared bottom navigation / explorer');const nn=f.findOne(n=>n.name==='App shell / Bottom navigation');
 if(oldNav&&nn)for(let i=0;i<4;i++)await nn.children[i].setReactionsAsync(oldNav.children[i].reactions);
}
const oldHome=legacyRoots[home.id];const oldUnknown=oldHome.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name.includes('unknown'));const unknown=home.findOne(n=>n.name==='Button/View order');if(oldUnknown&&unknown)await unknown.setReactionsAsync(oldUnknown.reactions);
const oldTrader=source.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name.includes('trader / trader-01'));const copy=home.findOne(n=>n.name==='Button/Open copying');if(copy){for(const t of copy.findAllWithCriteria({types:['TEXT']}))t.characters='Copy settings';copy.name='Button/Copy settings';await copy.setReactionsAsync(oldTrader.reactions.map(r=>({...r,actions:(r.actions||[r.action]).map(a=>a.type==='NODE'?{...a,destinationId:destinations.copy}:a)})));}
const posRoot=await figma.getNodeByIdAsync(destinations.positions);for(const n of home.findAllWithCriteria({types:['FRAME']}).filter(n=>n.name.startsWith('Position/'))){const rec=posRoot.findAllWithCriteria({types:['INSTANCE']}).find(x=>x.name.includes(' / '+n.name.slice(9)));if(rec)await n.setReactionsAsync(rec.reactions);}
for(const {n,target} of pending){if(n.name.startsWith('Nav/')||n.name==='Balance / Open wallets'||n.name==='Button/Notifications'||n.name==='Profile / Open account'||n.name==='Button/Copy settings'||n.name==='Button/View order'||n.name.startsWith('Position/'))continue;const dest=target==='home'?home.id:target==='catalogue'?catalogue.id:destinations[target];if(dest)await nav(n,dest);}
for(const {n,t} of traderNodes){n.setBoundVariable('visible',vm['Explore/EN/Data/catalog/show/'+t.id]);}
count.setBoundVariable('characters',vm['Explore/EN/Data/catalog/count']);
await nav(filters,destinations.filter,'OVERLAY');await nav(sort,destinations.sort,'OVERLAY');await nav(search,destinations.search,'OVERLAY');
const positives=source.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name.includes('Positive PnL'));if(positives)await positive.setReactionsAsync(positives.reactions);const cheap=source.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name.includes('Budget ≤ $50'));if(cheap)await budget.setReactionsAsync(cheap.reactions);
const att=home.findOne(n=>n.name==='Attention'),content=home.findOne(n=>n.name==='Page content');content.insertChild(2,att);
const result=session.children.find(n=>n.name==='Result');if(result)result.visible=false;const bd=session.children.find(n=>n.name==='Result breakdown');if(bd)bd.visible=false;
const pair=box(session,'Realized and unrealized',318,'VERTICAL',8);for(const [label,value] of [['Realized','+$1.22'],['Unrealized','+$8.55']]){const r=box(pair,'PnL row',318,'HORIZONTAL',8);text(r,'Label',label,'Body/Small','color/text/secondary',190);const t=text(r,'Value',value,'Numeric/Small','color/success/text',120);t.textAlignHorizontal='RIGHT';}session.insertChild(3,pair);
return {createdNodeIds:created,mutatedNodeIds:mutated,roots:[home.id,catalogue.id],legacyIds:Object.values(legacyRoots).map(n=>n.id),cardCount:traderNodes.length};
