const page = await figma.getNodeByIdAsync(CFG.pageId);
await figma.setCurrentPageAsync(page);
for (const style of ['Regular','Medium','Semi Bold','Bold']) await figma.loadFontAsync({family:'Inter',style});
const created=[]; const mutated=[];
const track=n=>{created.push(n.id);return n;};
const vars=await figma.variables.getLocalVariablesAsync();
const vm=Object.fromEntries(vars.map(v=>[v.name,v]));
const styles=await figma.getLocalTextStylesAsync();const sm=Object.fromEntries(styles.map(s=>[s.name,s]));
function paint(name){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',vm[name]);}
function color(n,name){n.fills=[paint(name)];}
function gap(n,value){n.itemSpacing=value;const v=vars.find(v=>v.name.startsWith('spacing/')&&Object.values(v.valuesByMode).includes(value));if(v)n.setBoundVariable('itemSpacing',v);}
function pad(n,value){for(const k of ['paddingTop','paddingBottom','paddingLeft','paddingRight']){n[k]=value;const v=vars.find(v=>v.name.startsWith('spacing/')&&Object.values(v.valuesByMode).includes(value));if(v)n.setBoundVariable(k,v);}}
function box(parent,name,w,dir='VERTICAL',spacing=16,bg=null,padding=0){const n=track(figma.createAutoLayout(dir));parent.appendChild(n);n.name=name;n.resize(w,10);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.layoutSizingVertical='HUG';n.fills=[];gap(n,spacing);pad(n,padding);if(bg){color(n,bg);n.cornerRadius=14;n.setBoundVariable('cornerRadius',vm['radius/lg']);n.strokes=[paint('color/border/default')];n.strokeWeight=1;}return n;}
function text(parent,name,value,style='Body/Small',tone='color/text/primary',width){const t=track(figma.createText());parent.appendChild(t);t.name=name;t.fontName=sm[style].fontName;t.textStyleId=sm[style].id;t.characters=value;color(t,tone);t.textAutoResize='HEIGHT';t.resize(width||Math.max(20,parent.width-parent.paddingLeft-parent.paddingRight),t.height);return t;}
function icon(parent,name,size=20){const svg=CFG.icons[name];if(!svg)return null;const n=track(figma.createNodeFromSvg(svg.replace(/currentColor/g,'#A3ADC2')));parent.appendChild(n);n.name='Icon/'+name;n.resize(size,size);for(const v of n.findAllWithCriteria({types:['VECTOR']})){created.push(v.id);if(v.strokes.length)v.strokes=v.strokes.map(p=>p.type==='SOLID'?paint('color/text/secondary'):p);if(v.fills.length)v.fills=v.fills.map(p=>p.type==='SOLID'?paint('color/text/secondary'):p);}return n;}
function expose(comp){for(const t of comp.findAllWithCriteria({types:['TEXT']})){const key=comp.addComponentProperty(t.name,'TEXT',t.characters);t.componentPropertyReferences={characters:key};}comp.description='Recovery reference component. Semantic role and token bindings preserved; use in review screens before rollout.';}
function props(inst,values){const out={};for(const [name,val] of Object.entries(values)){const k=Object.keys(inst.componentProperties).find(k=>k.split('#')[0]===name);if(k)out[k]=val;}inst.setProperties(out);for(const t of inst.findAllWithCriteria({types:['TEXT']})){if(Object.prototype.hasOwnProperty.call(values,t.name)){t.characters=values[t.name];created.push(t.id);}}}
function instance(parent,comp,name,width,values={}){const n=track(comp.createInstance());parent.appendChild(n);n.name=name;if(width)n.resize(width,n.height);n.layoutSizingVertical='HUG';props(n,values);return n;}
async function button(parent,label,width=160,primary=false){const comp=await figma.getNodeByIdAsync(primary?'113:240':'113:242');const n=track(comp.createInstance());parent.appendChild(n);n.name='Button/'+label;n.resize(width,48);for(const t of n.findAllWithCriteria({types:['TEXT']})){t.characters=label;created.push(t.id);}return n;}
async function nav(n,destination,navigation='NAVIGATE',extra=[]){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[...extra,{type:'NODE',destinationId:destination,navigation,transition:null,resetScrollPosition:false}]}]);mutated.push(n.id);}
function flex(t){t.layoutSizingHorizontal='FILL';}
function money(v,signed=false){if(v==null)return CFG.en?'No data':'Нет данных';let x=(Math.abs(v)/100).toFixed(2);if(!CFG.en)x=x.replace('.',',');return (v<0?'−':signed&&v>0?'+':'')+(CFG.en?'$'+x:x+' $');}
const maxX=page.children.reduce((a,n)=>Math.max(a,n.x+n.width),0)+160;
if(CFG.mode==='components'){
 const existing=page.children.find(n=>n.name==='Recovery 03 Oct / Components');if(existing)return {existingSection:existing.id,createdNodeIds:[],mutatedNodeIds:[]};
 const section=track(figma.createSection());section.name='Recovery 03 Oct / Components';section.x=maxX;section.y=0;section.resizeWithoutConstraints(1640,1200);
 const comps={};
 const candidates=[];
 for(const selected of [false,true]){
  const f=box(section,'NavItem',184,'HORIZONTAL',12,selected?'color/accent/subtle':null,12);f.counterAxisAlignItems='CENTER';f.resize(184,48);f.primaryAxisSizingMode='FIXED';icon(f,'house');text(f,'Label','Главная','Label',selected?'color/accent/text':'color/text/secondary',112);const c=track(figma.createComponentFromNode(f));c.name='Selected='+selected;expose(c);candidates.push(c);
 }
 const set=track(figma.combineAsVariants(candidates,section));set.name='Recovery/NavItem';set.x=40;set.y=40;set.resize(448,100);candidates.forEach((c,i)=>{c.x=16+i*208;c.y=16;});comps.navDefault=candidates[0].id;comps.navSelected=candidates[1].id;
 const metric=box(section,'Metric',276,'VERTICAL',8,'color/bg/surface',20);text(metric,'Label','Доступно','Body/Small','color/text/secondary');text(metric,'Value','180,38 $','Numeric/Large');text(metric,'Hint','Для новых покупок','Caption/Regular','color/text/secondary');const mc=track(figma.createComponentFromNode(metric));mc.name='Recovery/Metric';mc.x=40;mc.y=190;expose(mc);comps.metric=mc.id;
 const card=box(section,'TraderCard',350,'VERTICAL',16,'color/bg/surface',16);
 const identity=box(card,'Identity',318,'HORIZONTAL',12);identity.counterAxisAlignItems='CENTER';
 const av=box(identity,'Avatar',40,'VERTICAL',0,'color/accent/subtle',0);av.resize(40,40);av.primaryAxisSizingMode='FIXED';av.primaryAxisAlignItems='CENTER';av.counterAxisAlignItems='CENTER';text(av,'Initials','MF','Label','color/accent/text',24);
 const names=box(identity,'Name and venue',260,'VERTICAL',4);text(names,'Name','Momentum Fox','Heading/Small');text(names,'Venue','Polymarket','Caption/Regular','color/text/secondary');
 const metrics=box(card,'Metrics',318,'HORIZONTAL',16);for(const [key,label,value] of [['Pnl','PnL · 30 дней','+5,48 $'],['Drawdown','Макс. просадка','2,41%']]){const col=box(metrics,key,151,'VERTICAL',4);text(col,key+'Label',label,'Caption/Regular','color/text/secondary');text(col,key+'Value',value,key==='Pnl'?'Heading/Medium':'Heading/Small',key==='Pnl'?'color/success/text':'color/text/primary');}
 const footer=box(card,'Footer',318,'HORIZONTAL',8);text(footer,'Budget','От 50 $','Body/Small medium','color/text/primary',145);text(footer,'History','История 180 дней','Caption/Regular','color/text/secondary',165);
 const tc=track(figma.createComponentFromNode(card));tc.name='Recovery/TraderCard';tc.x=360;tc.y=190;expose(tc);comps.trader=tc.id;
 const search=box(section,'Search',350,'HORIZONTAL',12,'color/bg/surface',12);search.resize(350,48);search.primaryAxisSizingMode='FIXED';search.counterAxisAlignItems='CENTER';icon(search,'search');text(search,'Placeholder','Имя или адрес трейдера','Body/Small','color/text/secondary',292);const sc=track(figma.createComponentFromNode(search));sc.name='Recovery/Search';sc.x=760;sc.y=190;expose(sc);comps.search=sc.id;
 return {createdNodeIds:created,mutatedNodeIds:mutated,sectionId:section.id,components:comps};
}
const en=CFG.en;const L=(ru,enText)=>en?enText:ru;const desktop=CFG.desktop;const W=desktop?1440:390,H=desktop?960:844,inner=desktop?1152:350;
const sectionName='Recovery 03 Oct / Reference / '+(en?'EN':'RU');
if(page.children.some(n=>n.name===sectionName))return {exists:true,sectionId:page.children.find(n=>n.name===sectionName).id,createdNodeIds:[],mutatedNodeIds:[]};
const section=track(figma.createSection());section.name=sectionName;section.x=maxX;section.y=0;section.resizeWithoutConstraints(desktop?3120:1000,4000);
const comps={};for(const [k,id] of Object.entries(CFG.components))comps[k]=await figma.getNodeByIdAsync(id);
const destinations=CFG.destinations;
function root(name,x){const f=track(figma.createFrame());section.appendChild(f);f.name=name;f.resize(W,H);f.x=x;f.y=64;f.clipsContent=true;color(f,'color/bg/canvas');f.setExplicitVariableModeForCollection('VariableCollectionId:2:3','2:1');return f;}
const home=root(L('Главная · активное демо','Home · active demo'),40);const catalogue=root(L('Трейдеры','Traders'),desktop?1560:480);
const pending=[];
async function shell(f,which){
 if(desktop){const side=box(f,'App shell / Sidebar',224,'VERTICAL',8,'color/bg/surface',20);side.resize(224,H);side.primaryAxisSizingMode='FIXED';side.cornerRadius=0;side.x=0;side.y=0;
 text(side,'Brand','shadow','Brand','color/text/primary',184);const spacer=box(side,'Brand spacing',184,'VERTICAL',0);spacer.resize(184,20);spacer.primaryAxisSizingMode='FIXED';
 for(const [role,label,ic] of [['home',L('Главная','Home'),'house'],['catalogue',L('Трейдеры','Traders'),'users'],['positions',L('Позиции','Positions'),'layers'],['events',L('События','Events'),'activity']]){const n=instance(side,role===which?(comps['navSelected'+role]||comps.navSelected):(comps['navDefault'+role]||comps.navDefault),'Nav/'+role,184,{Label:label});pending.push({n,target:role});}
 const space=box(side,'Flexible spacer',184,'VERTICAL',0);space.layoutSizingVertical='FILL';const help=instance(side,comps.navDefault,'Nav/help',184,{Label:L('Помощь','Help')});pending.push({n:help,target:'help'});
 const h=track((await figma.getNodeByIdAsync('819:330')).createInstance());f.appendChild(h);h.name='Recovery/Header';h.resize(inner,68);h.x=256;h.y=24;props(h,{'Text 1':which==='home'?L('Главная','Home'):L('Трейдеры','Traders'),'Balance context':which==='home'?L('Ваше копирование и позиции','Your copying and positions'):L('Выберите трейдера для копирования','Choose a trader to copy'),'Balance context 3':L('Демо · доступно','Demo · available'),'Balance value':money(18038)});for(const t of h.findAllWithCriteria({types:['TEXT']}))if(t.boundVariables.characters)t.setBoundVariable('characters',null);
 for(const n of h.findAllWithCriteria({types:['FRAME']})){if(n.name==='Balance / Open wallets')pending.push({n,target:'funds'});if(n.name==='Button/Notifications')pending.push({n,target:'notifications'});if(n.name==='Button/Profile avatar')pending.push({n,target:'profile'});}
 }else{const h=track((await figma.getNodeByIdAsync('819:294')).createInstance());f.appendChild(h);h.name='Recovery/Header';h.resize(350,44);h.x=20;h.y=20;props(h,{'Brand':'shadow','Balance context':L('Демо · доступно','Demo · available'),'Balance value':money(18038)});for(const t of h.findAllWithCriteria({types:['TEXT']}))if(t.boundVariables.characters)t.setBoundVariable('characters',null);for(const n of h.findAllWithCriteria({types:['FRAME']})){if(n.name==='Balance / Open wallets')pending.push({n,target:'funds'});if(n.name==='Button/Notifications')pending.push({n,target:'notifications'});if(n.name==='Profile / Open account')pending.push({n,target:'profile'});}
 const bottom=box(f,'App shell / Bottom navigation',350,'HORIZONTAL',0,'color/bg/surface',0);bottom.resize(350,64);bottom.primaryAxisSizingMode='FIXED';bottom.x=20;bottom.y=760;
 for(const [role,label,ic] of [['home',L('Главная','Home'),'house'],['catalogue',L('Трейдеры','Traders'),'users'],['positions',L('Позиции','Positions'),'layers'],['events',L('События','Events'),'activity']]){const item=box(bottom,'Nav/'+role,87.5,'VERTICAL',4,role===which?'color/accent/subtle':null,8);item.resize(87.5,64);item.primaryAxisSizingMode='FIXED';item.counterAxisAlignItems='CENTER';icon(item,ic);const t=text(item,'Label',label,'Caption',role===which?'color/accent/text':'color/text/secondary',71.5);t.textAlignHorizontal='CENTER';pending.push({n:item,target:role});}
 }
 const viewport=box(f,'Scroll viewport',inner,'VERTICAL',0);viewport.resize(inner,desktop?832:664);viewport.primaryAxisSizingMode='FIXED';viewport.clipsContent=true;viewport.overflowDirection='VERTICAL';viewport.x=desktop?256:20;viewport.y=desktop?104:80;
 const content=box(viewport,'Page content',inner,'VERTICAL',desktop?24:16);content.paddingBottom=24;
 if(!desktop)text(content,'Page title',which==='home'?L('Главная','Home'):L('Трейдеры','Traders'),'Heading/Large');return content;
}
const hc=await shell(home,'home');const cc=await shell(catalogue,'catalogue');
if(desktop){const row=box(hc,'Account overview',inner,'HORIZONTAL',16);for(const [label,value,hint] of [[L('Стоимость демо-счёта','Demo account value'),money(20977),L('Результат +9,77 $','Result +$9.77')],[L('Доступно','Available'),money(18038),L('Для новых покупок','For new purchases')],[L('В позициях','In positions'),money(2360),L('5 текущих позиций','5 current positions')],[L('В резерве','Reserved'),money(579),L('Ожидающие заявки','Pending orders')]]){const m=instance(row,comps.metric,'Account metric',276,{Label:label,Value:value,Hint:hint});pending.push({n:m,target:'funds'});}}
else{const b=box(hc,'Demo account',350,'VERTICAL',8,'color/bg/surface',16);text(b,'Label',L('Стоимость демо-счёта','Demo account value'),'Body/Small','color/text/secondary');text(b,'Value',money(20977),'Numeric/Large');text(b,'Result',L('Результат копирования ','Copy result ')+money(977,true),'Body/Small medium','color/success/text');for(const [label,value] of [[L('Доступно','Available'),18038],[L('В резерве','Reserved'),579],[L('В позициях','In positions'),2360]]){const r=box(b,'Money row',318,'HORIZONTAL',8);text(r,'Label',label,'Body/Small','color/text/secondary',190);const t=text(r,'Amount',money(value),'Numeric/Small','color/text/primary',120);t.textAlignHorizontal='RIGHT';}pending.push({n:b,target:'funds'});}
let main=hc,right=null;if(desktop){const row=box(hc,'Workspace columns',inner,'HORIZONTAL',24);main=box(row,'Primary column',744);right=box(row,'Secondary column',384);}
const session=box(main,'Copy session',desktop?744:350,'VERTICAL',16,'color/bg/surface',desktop?24:16);text(session,'Heading',L('Копирование','Copying'),'Heading/Compact');const idrow=box(session,'Trader identity',session.width-2*session.paddingLeft,'HORIZONTAL',12);const names=box(idrow,'Identity',desktop?470:200,'VERTICAL',4);text(names,'Name','Momentum Fox','Heading/Small');text(names,'Venue','Polymarket','Body/Small','color/text/secondary');text(idrow,'Status',L('Активно','Active'),'Label','color/success/text',100);
text(session,'Result',money(977,true),'Numeric/Large','color/success/text');text(session,'Result breakdown',L('Реализовано +1,22 $ · Текущая оценка +8,55 $','Realized +$1.22 · Unrealized +$8.55'),'Body/Small','color/text/secondary');text(session,'Limits',L('На позицию 20 $ · Новые покупки 30 $ в день','Per position $20 · New purchases $30/day'),'Body/Small','color/text/secondary');const open=await button(session,L('Открыть копирование','Open copying'),desktop?224:318,true);pending.push({n:open,target:'copy'});
const positions=box(main,'Current positions',desktop?744:350,'VERTICAL',12,'color/bg/surface',desktop?24:16);const ph=box(positions,'Section heading',positions.width-2*positions.paddingLeft,'HORIZONTAL',8);const title=text(ph,'Heading',L('Текущие позиции · 5','Current positions · 5'),'Heading/Small',undefined,desktop?500:218);const all=await button(ph,L('Все','View all'),desktop?100:92);pending.push({n:all,target:'positions'});
for(const p of CFG.positions){const r=box(positions,'Position/'+p.id,positions.width-2*positions.paddingLeft,'HORIZONTAL',12);const col=box(r,'Market',desktop?490:192,'VERTICAL',4);text(col,'Market name',en?p.market:p.marketRu,'Body/Small medium');text(col,'Status',en?p.statusEn:p.statusRu,'Caption/Regular','color/text/secondary');const amounts=box(r,'Amounts',desktop?180:114,'VERTICAL',4);const v=text(amounts,'Value',money(p.markValueCents),'Numeric/Small');v.textAlignHorizontal='RIGHT';const pnl=text(amounts,'PnL',money(p.pnl,true),'Body/Small',p.pnl>=0?'color/success/text':'color/danger/text');pnl.textAlignHorizontal='RIGHT';pending.push({n:r,target:'positions'});}
const aside=right||hc;const attention=box(aside,'Attention',desktop?384:350,'VERTICAL',12,'color/warning/bg',16);text(attention,'Heading',L('Исход заявки уточняется','Order outcome is being checked'),'Heading/Small','color/warning/text');text(attention,'Explanation',L('Проверяем исполнение. Резерв сохраняется до подтверждения.','Execution is being checked. Funds remain reserved until confirmed.'),'Body/Small');const inspect=await button(attention,L('Посмотреть заявку','View order'),desktop?224:318);pending.push({n:inspect,target:'unknown'});
const events=box(aside,'Recent events',desktop?384:350,'VERTICAL',16,'color/bg/surface',16);text(events,'Heading',L('Последние события','Recent events'),'Heading/Small');for(const e of CFG.events){const row=box(events,'Event/'+e.id,events.width-32,'VERTICAL',4);text(row,'Event title',en?e.en:e.ru,'Body/Small medium');text(row,'Event meta',e.time+' · '+(en?e.statusEn:e.statusRu),'Caption/Regular','color/text/secondary');pending.push({n:row,target:'events'});}const ea=await button(events,L('Все события','All events'),desktop?200:318);pending.push({n:ea,target:'events'});
const toolbar=box(cc,'Catalogue toolbar',inner,desktop?'HORIZONTAL':'VERTICAL',12);const search=instance(toolbar,comps.search,'Input/Search',desktop?668:350,{Placeholder:L('Имя или адрес трейдера','Trader name or address')});const controlrow=desktop?toolbar:box(toolbar,'Filter and sort',350,'HORIZONTAL',12);const filters=await button(controlrow,L('Фильтры','Filters'),desktop?160:132);const sort=await button(controlrow,L('По PnL ▾','By PnL ▾'),desktop?300:206);
const chips=box(cc,'Collections',inner,'HORIZONTAL',12);const positive=await button(chips,L('PnL > 0','PnL > 0'),desktop?144:132);const budget=await button(chips,L('Бюджет до 50 $','Budget ≤ $50'),desktop?196:206);const count=text(cc,'Result count',L('24 трейдера · 30 дней','24 traders · 30 days'),'Body/Small','color/text/secondary');
const list=box(cc,'Trader grid',inner,'VERTICAL',16);const traderNodes=[];let gridrow;
for(let i=0;i<CFG.traders.length;i++){const t=CFG.traders[i];if(desktop&&i%3===0)gridrow=box(list,'Grid row '+Math.floor(i/3),inner,'HORIZONTAL',16);const n=instance(desktop?gridrow:list,comps.trader,'Trader/'+t.id,desktop?373.33:350,{Initials:t.name.split(' ').map(x=>x[0]).join(''),Name:t.name,Venue:t.venue==='polymarket'?'Polymarket':'Limitless',PnlLabel:L('PnL · 30 дней','PnL · 30 days'),PnlValue:money(t.publicPnlCents,true),DrawdownLabel:L('Макс. просадка','Max drawdown'),DrawdownValue:t.drawdownBasisPoints==null?'—':(t.drawdownBasisPoints/100).toFixed(2).replace('.',en?'.':',')+'%',Budget:L('От ','From ')+money(t.minimumBudgetCents),History:L('История ','History ')+t.historyDays+L(' дней',' days')});const v=n.findAllWithCriteria({types:['TEXT']}).find(x=>x.name==='PnlValue');if(v)color(v,t.publicPnlCents==null?'color/text/secondary':t.publicPnlCents>=0?'color/success/text':'color/danger/text');traderNodes.push({n,t});}
// Retain the existing record initialization and detail destination for each trader.
const source=await figma.getNodeByIdAsync(destinations.catalogueOld);
for(const {n,t} of traderNodes){const old=source.findAllWithCriteria({types:['INSTANCE']}).find(x=>x.name.includes('trader / '+t.id));if(old){await n.setReactionsAsync(old.reactions);mutated.push(n.id);}}
const filterSheet=box(section,'Filter panel',desktop?440:350,'VERTICAL',16,'color/bg/surface',24);filterSheet.x=40;filterSheet.y=1100;
text(filterSheet,'Title',L('Фильтры','Filters'),'Heading/Medium');text(filterSheet,'Scope',L('Период: 30 дней · обе площадки','Period: 30 days · both venues'),'Body/Small','color/text/secondary');const pf=await button(filterSheet,L('Положительный PnL','Positive PnL'),desktop?392:302);const bf=await button(filterSheet,L('Бюджет до 50 $','Budget ≤ $50'),desktop?392:302);const reset=await button(filterSheet,L('Сбросить фильтры','Reset filters'),desktop?392:302);const close=await button(filterSheet,L('Готово','Done'),desktop?392:302,true);await close.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'CLOSE'}]}]);mutated.push(close.id);
const sortSheet=box(section,'Sort panel',desktop?360:350,'VERTICAL',12,'color/bg/surface',24);sortSheet.x=desktop?600:480;sortSheet.y=1100;text(sortSheet,'Title',L('Сортировка','Sort by'),'Heading/Medium');const defaultSort=await button(sortSheet,L('Исходный порядок','Default order'),desktop?312:302);const pnlSort=await button(sortSheet,L('PnL: от большего','PnL: high to low'),desktop?312:302);const sortClose=await button(sortSheet,L('Закрыть','Close'),desktop?312:302);await sortClose.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'CLOSE'}]}]);mutated.push(sortClose.id);
// A bounded reference interaction: variables control visibility; overlays do not replace the catalogue.
const coll=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:882:7');const visibility=[];
for(const {n,t} of traderNodes){const name='Recovery/'+page.id+'/'+t.id+'/visible';let v=vm[name];if(!v){v=figma.variables.createVariable(name,coll,'BOOLEAN');v.scopes=['ALL_SCOPES'];v.setValueForMode(coll.defaultModeId,true);}n.setBoundVariable('visible',v);visibility.push({v,t});}
let cv=vm['Recovery/'+page.id+'/count'];if(!cv){cv=figma.variables.createVariable('Recovery/'+page.id+'/count',coll,'STRING');cv.scopes=['TEXT_CONTENT'];cv.setValueForMode(coll.defaultModeId,L('24 трейдера · 30 дней','24 traders · 30 days'));}count.setBoundVariable('characters',cv);
async function applyFilter(n,predicate,label){const actions=visibility.map(({v,t})=>({type:'SET_VARIABLE',variableId:v.id,variableValue:{type:'BOOLEAN',resolvedType:'BOOLEAN',value:predicate(t)}}));actions.push({type:'SET_VARIABLE',variableId:cv.id,variableValue:{type:'STRING',resolvedType:'STRING',value:CFG.traders.filter(predicate).length+L(' трейдера · 30 дней',' traders · 30 days')}});await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions}]);mutated.push(n.id);}
await applyFilter(positive,t=>t.publicPnlCents>0,'positive');await applyFilter(pf,t=>t.publicPnlCents>0,'positive');await applyFilter(budget,t=>t.minimumBudgetCents<=5000,'budget');await applyFilter(bf,t=>t.minimumBudgetCents<=5000,'budget');await applyFilter(reset,t=>true,'reset');
await nav(filters,filterSheet.id,'OVERLAY');await nav(sort,sortSheet.id,'OVERLAY');
// Sorting is deferred to the separate sorted reference state in the next safe construction phase.
for(const {n,target} of pending){const dest=target==='home'?home.id:target==='catalogue'?catalogue.id:destinations[target];let ancestor=n;while(ancestor&&ancestor.type!=='PAGE'&&ancestor.id!==home.id&&ancestor.id!==catalogue.id)ancestor=ancestor.parent;if(dest&&ancestor?.id!==dest)await nav(n,dest,'NAVIGATE',[{type:'SET_VARIABLE',variableId:'VariableID:830:2',variableValue:{type:'STRING',resolvedType:'STRING',value:'active'}},{type:'SET_VARIABLE',variableId:en?'VariableID:830:5':'VariableID:830:4',variableValue:{type:'STRING',resolvedType:'STRING',value:money(18038)}}]);}
const roots=[home,catalogue];return {createdNodeIds:created,mutatedNodeIds:mutated,sectionId:section.id,homeId:home.id,catalogueId:catalogue.id,filterPanelId:filterSheet.id,sortPanelId:sortSheet.id,sortButtons:{default:defaultSort.id,pnl:pnlSort.id},searchId:search.id,countId:count.id,traders:traderNodes.map(({n,t})=>({id:n.id,traderId:t.id,pnl:t.publicPnlCents})),editability:roots.map(f=>({id:f.id,texts:f.findAllWithCriteria({types:['TEXT']}).length,instances:f.findAllWithCriteria({types:['INSTANCE']}).length,images:f.findAllWithCriteria({types:['RECTANGLE','FRAME']}).filter(n=>Array.isArray(n.fills)&&n.fills.some(p=>p.type==='IMAGE')).length}))};
